### PR TITLE
Versioned setup

### PR DESCRIPTION
**Pull request by tomwendel**
This pr takes the assembly version of the antme.exe to use it as the product version of the installer

### CODE REVIEW

**Review by TheBlubb14 — COMMENTED** [review]
grafik
Is the revision number related to this, or how do i see the version of the installer?

**Comment by tomwendel** [comment]
I installed it. the list of installed programs tells you the version. but good question what the revision is. I only replaced the version attribute. let me find out what professional MSIs show up in the file details

**Comment by tomwendel** [comment]
So reviewed a bunch of other msi files. All of them have a guid as revison number and no hint about versions in the file detail.

**Review by TheBlubb14 — APPROVED** [review]
The product is still called AntMe 1.7, while we are on version 1.8, but otherwise LGTM

**Comment by tomwendel** [comment]
This is because of the automatic version generation and the lag of a proper tag yet. As soon as we have a relaese and a tag "v1.7.4" it will generate a proper version number

**Pull request merged**
