### PR TITLE
Bugfix

### PR DESCRIPTION
**Pull request by patrick-h-schwarz**
ants that move fruits will now die after they have reached maximum reach

### CODE REVIEW

**Comment by patteki** [comment]
Hi Patrick, 
Thanks for reporting and providing a Fix for this Bug, 
I looked already into it, but I have to check back, if your solution is enough to fix it in total.

**Comment by patteki** [comment]
Hi @patrick-h-schwarz,
sry it took so long. 
I looked into your change and one small thing I would like to see you to change before merging this in.
Your current implementation substracts/adds the current speed of the ant from the rest-/totalDistance of the ant. But actually the ant just get moved by a fraction of this value, calculated by the number of ants pulling on the apple and their directions. 
In terms of energy put into moving the apple this would be the right way, but from a user perspective this creates an unpredictable problem of  how far the ant traveled/can travel.
To prevent such a problem, we decided, it would be better to substract/add not the current speed but the actual traveled distance, the distance the ant(s) moved the apple.
So please change your fix to make sure the distance is calculated correctly. I think you can use the dx/dy values to determin the the traveled distance and subtract/add this value instead.
Thanks for your work so far, looking forward to your fix and if you need any assistance just reach out to me.

Cheers Patrick

**Comment by patrick-h-schwarz** [comment]
Hi, 
I did the update. Keep up the great work

**Review by patteki — APPROVED** [review]
Thanks for the quick fix!

Have fun coding your ants :D

Cheers Patrick

**Review by tomwendel — APPROVED** [review]
Bugfixes within the simulation core after such a long (stable) time... :D Love it. Thanks Patrick

**Pull request merged**
